### ISSUE TITLE
Error in TOML

### ISSUE THREAD

**Issue by ybabel** [norweeg/self-hosted-docker-server-templates#1]
https://github.com/norweeg/self-hosted-docker-server-templates/blob/246554840bdc09b647d6d73dd43f9439cc463cfe/configs/traefik.toml#L72

I got an error `Error reading TOML config file /etc/traefik/traefik.toml : toml: cannot load TOML value of type string into a Go boolean`

I think it's `dashboard = true` instead of `dashboard = "true"`

**Comment by norweeg** [comment]
Have you tested this change and confirmed that it works?  If so, I can change it, or if you want to open a pull request for the fix, I can merge it

**Comment by norweeg** [comment]
just checked my own TOML file and you are correct.  Goofed because in the compose file YAML, you don't want the true to be converted to a boolean, but in the TOML, you do.  I'll put the fix in and credit you.  Thanks for brining this to my attention!
