### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by TheHackmeister** [norweeg/self-hosted-docker-server-templates#3]
Hello,
I ran across this project yesterday on Reddit, and realized it was pretty close to [TechnoCore](https://github.com/SciFiFarms/TechnoCore), a project I'm working on. It also shares some similarities to [Home Assistant/Hass.io addons](https://www.home-assistant.io/addons/). There are some pretty big differences in approach, but if you ever need some ideas, those might be good places to look. 

Not that you're in need of ideas. I liked the way you made the compose file dynamic. I had considered something similar and having seen it work, am likely to move in that direction. So if you're interested in working in a similar direction, we should coordinate a time to chat.

**Comment by norweeg** [comment]
sounds good!  I'll check these out
