### ISSUE TITLE
Traefik Setup

### ISSUE THREAD

**Issue by X1Aaron** [norweeg/self-hosted-docker-server-templates#4]
Can you please explain how to correctly setup Traefik? I am running on Ubuntu 18.04.

I keep getting:

ERROR: Invalid interpolation format for "labels" option in service "reverse-proxy": "traefik.frontend.rule=Host:${TRAEFIK_DASHBOARD_URL:?Please set the value of TRAEFIK_DASHBOARD_URL in .env or comment this line out}"
 Even after I did sent it in .env - I set it to traefik.domain.com

Also, I am not sure how to go about generating the password file. It says: Run htdigest -c /path/to/new/password/file traefik yourusername to create a username/password for the traefik dashboard and set TRAEFIK_USERS_PASSWORD_FILE in .env to the path of the file

Where do I run Run htdigest -c /path/to/new/password/file traefik yourusername? On the host? What password does this set?

I think I am a little confused. I have been trying to read the traefik documentation to understand better,

**Comment by norweeg** [comment]
Did you happen to include an http:// or https:// in the value of that variable?  If so, drop that, just include the hostname e.g. dashboard.mydomain.com instead of http://dashboard.mydomain.com

**Comment by norweeg** [comment]
as for htdigest, you run that in the command line of your host system.  Running this command creates a password file on your host system that you mount as a volume in your traefik container that you can then use to secure services that don't have their own password protection.  If you don't already have it installed, you will need to install apache2-utils with `sudo apt-get install apache2-utils`.   Ubuntu is nice enough to tell you this if you try to run it without installing it first (that's what I did).  Securing pages was a late edition to the project, so looks like I forgot to document it.  I'll fix that.  Until then, [here's a good explanation of what it is/does](https://www.geeksforgeeks.org/htdigest-command-in-linux-with-examples/)

**Comment by norweeg** [comment]
@aaronstuder I just committed two changes to address this.  First, I changed TRAEFIK_DASHBOARD_URL to TRAEFIK_DASHBOARD_DOMAIN to make it unambiguous what you need to put here (that is, don't add the https:// part of a URL, just put in a domain).  Second, I added a section about using htpasswd and htdigest.  If this looks good to you, I will go ahead and close this issue

**Comment by norweeg** [comment]
I'm going to close this issue now that I've added documentation on these topics, if that's okay
