### ISSUE TITLE
docker-compose ... config fails

### ISSUE THREAD

**Issue by NSchnitzler** [norweeg/self-hosted-docker-server-templates#5]
docker-compose -f docker-compose.base.yaml config causes:
```
ERROR: The Compose file './docker-compose.base.yaml' is invalid because:
networks.docker-gui-network value Additional properties are not allowed ('name' was unexpected)
services.docker-gui.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
```
any idea how to fix this?

thanks in advance

Norbert

**Comment by norweeg** [comment]
what versions of docker and docker-compose do you have??  It's possible you have an older versions that aren't compatible with the templates.

`docker-compose --version` and `docker --version` to get the versions.  The system I am developing on has docker-compose version 1.24.0, build 0aa59064 with Docker version 18.09.6, build 481bc77

**Comment by NSchnitzler** [comment]
Hi,

i am using an Ubuntu Server system with docker-compose version 1.17.1, build unknown and Docker version 18.09.5, build e8ff056
But i have no pending updates which i could install.

**Comment by norweeg** [comment]
according to the [compatibility matrix](https://docs.docker.com/compose/compose-file/), that version of docker is sufficient (the templates are using docker-compose file version 3.5 syntax), but that docker-compose version is quite old.  Did you install it from the ubuntu repositories??   If so, I recommend you uninstall it and install docker-compose following their [installation documentation ](https://docs.docker.com/compose/install/) instead.  Ubuntu has old versions in their standard repository and they rarely update.  Update your compose version and try again.  Let me know how that goes

**Comment by NSchnitzler** [comment]
yes, i had the ubuntu repo version installed, but now switched to the recommend installation version. 
This has solved the issue mentioned above. Thanks for that.
